"use client";
import {useState} from "react";
import {Home,UserRound,CalendarDays,HeartPulse,ShieldCheck,CreditCard,Sparkles,Menu,X,ChevronRight,Check,Settings} from "lucide-react";
import {AuthGate} from "./auth-gate";
import {ManagerPortal} from "./manager-portal";
import {neon} from "@/lib/neon";
type View="home"|"profile"|"dates"|"health"|"consent"|"payment"|"passport";
const nav=[
 ["home",Home],["profile",UserRound],["dates",CalendarDays],["health",HeartPulse],["consent",ShieldCheck],["payment",CreditCard],["passport",Sparkles]
] as const;
type Lang="DE"|"FR"|"EN"|"ES"|"ZH";
const copy={
DE:{nav:["Übersicht","Kind & Familie","Kurs & Termine","Gesundheit","Einwilligungen","Zahlung","Dschungelpass"],portal:"FAMILIENPORTAL",due:"Zahlung offen",dueText:"Die erste Barzahlung über 105 € ist seit 1. September fällig.",details:"Details ansehen",active:"Aktives Kind",hello:"GUTEN MORGEN, FAMILIE BEISPIEL",hero:"Mias Dschungel-Abenteuer beginnt.",heroText:"Alles Wichtige zum Kurs an einem ruhigen Ort, schnell erreichbar und auch unterwegs.",go:"Los geht’s!",quick:"Schnellaktion",absence:"Abwesenheit melden",reported:"Abwesenheit gemeldet",payStatus:"Zahlungsstatus",overdue:"105 € überfällig",next:"NÄCHSTER TERMIN",confirmed:"Bestätigt",allDates:"Alle Termine ansehen",passport:"DSCHUNGELPASS",tracks:"11 von 21 Spuren",remaining:"Noch 10 Spuren bis zum Dschungel-Champion.",progress:"Fortschritt öffnen",privacy:"Deine Angaben bleiben geschützt.",preview:"Diese Vorschau verwendet ausschließlich Beispieldaten."},
FR:{nav:["Aperçu","Enfant et famille","Cours et dates","Santé","Autorisations","Paiement","Passeport jungle"],portal:"PORTAIL FAMILLE",due:"Paiement en attente",dueText:"Le premier paiement en espèces de 105 € est dû depuis le 1er septembre.",details:"Voir les détails",active:"Enfant actif",hello:"BONJOUR, FAMILLE EXEMPLE",hero:"L’aventure jungle de Mia commence.",heroText:"Toutes les informations du cours au même endroit, faciles à consulter même en déplacement.",go:"C’est parti !",quick:"Action rapide",absence:"Signaler une absence",reported:"Absence signalée",payStatus:"Statut du paiement",overdue:"105 € en retard",next:"PROCHAIN COURS",confirmed:"Confirmé",allDates:"Voir toutes les dates",passport:"PASSEPORT JUNGLE",tracks:"11 traces sur 21",remaining:"Encore 10 traces avant le titre de champion de la jungle.",progress:"Voir les progrès",privacy:"Vos informations restent protégées.",preview:"Cet aperçu utilise uniquement des données d’exemple."},
EN:{nav:["Overview","Child & family","Course & dates","Health","Consent","Payment","Jungle passport"],portal:"FAMILY PORTAL",due:"Payment due",dueText:"The first €105 cash payment has been due since 1 September.",details:"View details",active:"Active child",hello:"GOOD MORNING, EXAMPLE FAMILY",hero:"Mia’s jungle adventure begins.",heroText:"Everything important about the course in one calm place, easy to reach on the go.",go:"Let’s go!",quick:"Quick action",absence:"Report an absence",reported:"Absence reported",payStatus:"Payment status",overdue:"€105 overdue",next:"NEXT SESSION",confirmed:"Confirmed",allDates:"View all dates",passport:"JUNGLE PASSPORT",tracks:"11 of 21 tracks",remaining:"10 more tracks to become Jungle Champion.",progress:"Open progress",privacy:"Your information stays protected.",preview:"This preview uses example data only."},
ES:{nav:["Resumen","Niño y familia","Curso y fechas","Salud","Consentimientos","Pago","Pasaporte selva"],portal:"PORTAL FAMILIAR",due:"Pago pendiente",dueText:"El primer pago en efectivo de 105 € está pendiente desde el 1 de septiembre.",details:"Ver detalles",active:"Niño activo",hello:"BUENOS DÍAS, FAMILIA DE EJEMPLO",hero:"Comienza la aventura en la selva de Mia.",heroText:"Toda la información importante del curso en un solo lugar, también desde el móvil.",go:"¡Vamos!",quick:"Acción rápida",absence:"Avisar de una ausencia",reported:"Ausencia registrada",payStatus:"Estado del pago",overdue:"105 € atrasados",next:"PRÓXIMA CLASE",confirmed:"Confirmado",allDates:"Ver todas las fechas",passport:"PASAPORTE SELVA",tracks:"11 de 21 huellas",remaining:"Faltan 10 huellas para ser Campeona de la Selva.",progress:"Ver progreso",privacy:"Tus datos permanecen protegidos.",preview:"Esta vista previa solo utiliza datos de ejemplo."},
ZH:{nav:["概览","孩子与家庭","课程与日期","健康","同意事项","付款","丛林护照"],portal:"家庭门户",due:"待付款",dueText:"首笔105欧元现金款自9月1日起已到期。",details:"查看详情",active:"当前孩子",hello:"早上好，示例家庭",hero:"米娅的丛林冒险开始了。",heroText:"课程重要信息集中在一个简洁页面，外出时也能轻松查看。",go:"出发！",quick:"快捷操作",absence:"报告缺席",reported:"已报告缺席",payStatus:"付款状态",overdue:"105欧元逾期",next:"下一节课",confirmed:"已确认",allDates:"查看所有日期",passport:"丛林护照",tracks:"21枚足迹中已获11枚",remaining:"再获得10枚足迹即可成为丛林冠军。",progress:"查看进度",privacy:"您的信息会受到保护。",preview:"此预览仅使用示例数据。"}
} as const;
const skills=[["🐒","Klettern & Hangeln",3],["🦩","Balance",2],["🐼","Rollen",2],["🦘","Springen & Landen",2],["🐻","Krabbeln & Stützen",1],["🦜","Koordination",1]] as const;
export default function Page(){
 return <AuthGate><Portal/></AuthGate>;
}
function Portal(){
 const [view,setView]=useState<View>("home"),[menu,setMenu]=useState(false),[absence,setAbsence]=useState(false),[reported,setReported]=useState(false),[toast,setToast]=useState(""),[mode,setMode]=useState<"family"|"manager">("manager"),[language,setLanguage]=useState<Lang>("DE");
 const session=neon.auth.useSession();
 const signedInEmail=session.data?.user.email?.toLowerCase()??"";
 const authRole=(session.data?.user as {role?:string}|undefined)?.role;
 const isManager=authRole==="admin"||signedInEmail===process.env.NEXT_PUBLIC_MANAGER_EMAIL?.toLowerCase();
 const t=copy[language];
 const go=(v:View)=>{setView(v);setMenu(false);scrollTo({top:0,behavior:"smooth"})}; const save=(s:string)=>{setToast(s);setTimeout(()=>setToast(""),2500)};
 if(mode==="manager"&&isManager) return <ManagerPortal exit={()=>setMode("family")}/>;
 return <div className="shell">
  <aside className={menu?"side open":"side"}><button className="side-x" onClick={()=>setMenu(false)}><X/></button><div className="brand"><span>TR</span><div>Train With<br/><b>Rahil</b></div></div><nav>{nav.map(([id,Icon],i)=><button className={view===id?"active":""} onClick={()=>go(id)} key={id}><Icon size={19}/>{t.nav[i]}</button>)}</nav>{isManager&&<button className="manager-link" onClick={()=>setMode("manager")}><Settings size={17}/> Manager</button>}<div className="account"><i>{signedInEmail.slice(0,2).toUpperCase()||"ME"}</i><div><b>{session.data?.user.name||"Mein Konto"}</b><small>{signedInEmail}</small></div></div></aside>
  <main><div className="due-banner"><b>{t.due}</b><span>{t.dueText}</span><button onClick={()=>go("payment")}>{t.details}</button></div><header><button className="hamb" onClick={()=>setMenu(true)}><Menu/></button><div><small>{t.portal}</small><h1>{t.nav[nav.findIndex(x=>x[0]===view)]}</h1></div><select className="language" value={language} onChange={e=>setLanguage(e.target.value as Lang)} aria-label="Language"><option value="DE">🇩🇪 Deutsch</option><option value="FR">🇫🇷 Français</option><option value="EN">🇬🇧 English</option><option value="ES">🇪🇸 Español</option><option value="ZH">🇨🇳 中文</option></select><button className="child"><i>M</i><span><small>{t.active}</small><b>Mia Beispiel</b></span><ChevronRight size={16}/></button></header>
  <div className="content">
   {view==="home"&&<Dashboard go={go} absence={()=>setAbsence(true)} reported={reported} t={t}/>} 
   {view==="profile"&&<Card title="Kind & Familie" intro="Kontaktdaten für einen sicheren, unkomplizierten Kursalltag."><div className="person"><i>M</i><div><h3>Mia Beispiel</h3><p>Geboren am 18.04.2020 · Klasse GS</p></div><Tag>Aktiv</Tag></div><div className="form"><Field l="Vorname des Kindes" v="Mia"/><Field l="Nachname" v="Beispiel"/><Field l="Geburtsdatum" v="18.04.2020"/><Field l="Klasse" v="GS"/><Field l="Erziehungsberechtigte Person" v="Maria Beispiel"/><Field l="Mobilnummer" v="+49 170 1234567"/><Field l="E-Mail" v="mia@example.de"/><Field l="Weitere Bezugsperson" v="Daniel Beispiel"/></div><button className="primary" onClick={()=>save("Profil gespeichert")}>Änderungen speichern</button></Card>}
   {view==="dates"&&<Dates report={()=>setAbsence(true)} reported={reported}/>} 
   {view==="health"&&<Card title="Gesundheit & Notfall" intro="Nur Angaben, die für eine sichere Betreuung wirklich nötig sind."><Notice icon="♥" title="Bitte aktuell halten">Im Notfall kontaktieren wir zuerst die angegebene Person.</Notice><label>Allergien, Erkrankungen oder wichtige Hinweise<textarea defaultValue="Keine bekannten Allergien."/></label><div className="form"><Field l="Notfallkontakt" v="Maria Beispiel"/><Field l="Telefon im Notfall" v="+49 170 1234567"/></div><label className="check"><input type="checkbox" defaultChecked/> Ich bestätige, dass die Angaben aktuell sind.</label><button className="primary" onClick={()=>save("Gesundheitsangaben gespeichert")}>Sicher speichern</button></Card>}
   {view==="consent"&&<Card title="Foto & Video" intro="Du entscheidest einzeln und kannst deine Auswahl später ändern."><Toggle title="Interne Kursdokumentation" text="Fotos nur für die teilnehmenden Familien." initial/><Toggle title="Informationen der Schule" text="Ausgewählte Aufnahmen in geschützten Schulkanälen."/><Toggle title="Öffentliche Kommunikation" text="Website oder soziale Medien; Namen werden nicht veröffentlicht."/><p className="fine">Eine Ablehnung hat keinen Einfluss auf Mias Teilnahme.</p><button className="primary" onClick={()=>save("Einwilligungen gespeichert")}>Auswahl speichern</button></Card>}
   {view==="payment"&&<Payment/>}{view==="passport"&&<Passport/>}
  </div></main>
  {absence&&<div className="backdrop" onMouseDown={()=>setAbsence(false)}><section className="modal" onMouseDown={e=>e.stopPropagation()}><button className="modal-x" onClick={()=>setAbsence(false)}><X/></button><div className="big-animal">🦜</div><small className="over">SCHNELL GEMELDET</small><h2>Mia ist nicht dabei?</h2><p>Die Abmeldung gilt für den gewählten Kurstermin. Ein Grund ist freiwillig.</p><label>Termin<select><option>Dienstag, 15. September · 14:10</option><option>Dienstag, 22. September · 14:10</option></select></label><label>Hinweis (optional)<textarea placeholder="z. B. Arzttermin"/></label><button className="primary wide" onClick={()=>{setReported(true);setAbsence(false);save("Abwesenheit gemeldet")}}>Abwesenheit melden</button><button className="cancel" onClick={()=>setAbsence(false)}>Abbrechen</button></section></div>}
  {toast&&<div className="toast"><Check size={18}/>{toast}</div>}
 </div>
}
function Dashboard({go,absence,reported,t}:{go:(v:View)=>void;absence:()=>void;reported:boolean;t:(typeof copy)[Lang]}){return <><section className="hero"><div><small>{t.hello}</small><h2>{t.hero}</h2><p>{t.heroText}</p></div><div className="monkey"><img src="/jungle-monkey.png" alt="Cheerful monkey climbing a vine"/><b>{t.go}</b></div></section><div className="quick-grid"><button className="quick orange" onClick={absence}><i>✋</i><span><small>{t.quick}</small><b>{reported?t.reported:t.absence}</b></span><ChevronRight/></button><button className="quick blue" onClick={()=>go("payment")}><i>€</i><span><small>{t.payStatus}</small><b>{t.overdue}</b></span><ChevronRight/></button></div><div className="two"><section className="box"><div className="box-head"><div><small className="over">{t.next}</small><h3>Jungle Gymnastics</h3></div><Tag>{t.confirmed}</Tag></div><div className="next"><i><b>15</b><small>SEP</small></i><div><b>Dienstag · 14:10 bis 16:00</b><p>Lycée Jean Renoir · GS</p></div></div><button className="secondary" onClick={()=>go("dates")}>{t.allDates} <ChevronRight size={16}/></button></section><section className="box"><div className="box-head"><div><small className="over">{t.passport}</small><h3>{t.tracks}</h3></div><span className="lion">🦁</span></div><div className="bar"><i/></div><p className="muted">{t.remaining}</p><div className="animals">{skills.slice(0,5).map(x=><i key={x[0]}>{x[0]}</i>)}</div><button className="secondary" onClick={()=>go("passport")}>{t.progress} <ChevronRight size={16}/></button></section></div><Notice icon="✓" title={t.privacy}>{t.preview}</Notice></>}
function Dates({report,reported}:{report:()=>void;reported:boolean}){return <Card title="Kurs & Termine" intro="Jungle Gymnastics · Dienstags von 14:10 bis 16:00 Uhr."><div className="course"><span>🐒</span><div><b>Lycée Jean Renoir</b><p>GS · Leitung: Rahil Wasiq</p></div></div><div className="dates">{["15. September","22. September","29. September","6. Oktober"].map((d,i)=><div key={d}><i>{i+1}</i><span><b>Dienstag, {d}</b><p>14:10–16:00 · Schulgebäude</p></span>{i===0&&reported?<Tag>Abgemeldet</Tag>:<button onClick={report}>Abmelden</button>}</div>)}</div></Card>}
function Payment(){const[p,setP]=useState("four"),[saved,setSaved]=useState(false);const rows=p==="four"?["1. Rate · 1. September","2. Rate · 1. November","3. Rate · 1. Januar","4. Rate · 1. März"]:["Gesamtbetrag · 1. September"];return <Card title="Zahlung" intro="Jahresbeitrag für Jungle Gymnastics: 420 €. Die Zahlung erfolgt bar."><div className="pay"><div><small className="over">STATUS</small><h3>Zahlung fällig</h3><p>Der Status wird grün, sobald Rahil den Barbetrag bestätigt.</p></div><b>{p==="four"?"105 €":"420 €"}</b></div><h3>Zahlungsweise wählen</h3><div className="plans"><button className={p==="one"?"selected":""} onClick={()=>setP("one")}><span><b>Alles zusammen</b><small>1 × 420 € bar</small></span>{p==="one"&&<Check/>}</button><button className={p==="four"?"selected":""} onClick={()=>setP("four")}><span><b>Vier Raten</b><small>4 × 105 € bar</small></span>{p==="four"&&<Check/>}</button></div><button className="primary" onClick={()=>setSaved(true)}>{saved?"Auswahl gespeichert":"Zahlungsweise speichern"}</button><div className="installments">{rows.map((x,i)=><div key={x}><span><b>{x}</b><small>{p==="four"?"105 €":"420 €"} · Barzahlung</small></span><em className={i?"pending":"overdue"}>{i?"Offen":"Überfällig"}</em></div>)}</div><p className="fine">Nur der Clubmanager kann eine Barzahlung als erhalten bestätigen.</p></Card>}
function Passport(){return <Card title="Mias Dschungelpass" intro="Kleine Schritte, mutige Bewegungen – jede Spur zeigt, was Mia schon entdeckt hat."><div className="skills">{skills.map(([a,n,count])=><div className="skill" key={n}><i>{a}</i><div><b>{n}</b><p>{count} von 3 Spuren</p><span>{[0,1,2].map(j=><i className={j<count?"done":""} key={j}>{j<count?"✓":""}</i>)}</span></div></div>)}</div><div className="champ"><span>🦁</span><div><small>DAS GROSSE ZIEL</small><h3>Dschungel-Champion</h3><p>Wenn alle Bewegungswelten entdeckt sind, wartet die Löwen-Auszeichnung.</p></div></div></Card>}
function Card({title,intro,children}:{title:string;intro:string;children:React.ReactNode}){return <section className="page"><div className="title"><small>MIA BEISPIEL</small><h2>{title}</h2><p>{intro}</p></div>{children}</section>}
function Field({l,v}:{l:string;v:string}){return <label>{l}<input defaultValue={v}/></label>}
function Tag({children}:{children:React.ReactNode}){return <span className="tag">{children}</span>}
function Notice({icon,title,children}:{icon:string;title:string;children:React.ReactNode}){return <section className="notice"><i>{icon}</i><div><b>{title}</b><p>{children}</p></div></section>}
function Toggle({title,text,initial=false}:{title:string;text:string;initial?:boolean}){const[on,setOn]=useState(initial);return <div className="toggle"><div><b>{title}</b><p>{text}</p></div><button className={on?"on":""} onClick={()=>setOn(!on)} role="switch" aria-checked={on}><i/></button></div>}
