"use client";
import {useState} from "react";
import {Home,UserRound,CalendarDays,HeartPulse,ShieldCheck,CreditCard,Sparkles,Menu,X,ChevronRight,Check} from "lucide-react";
type View="home"|"profile"|"dates"|"health"|"consent"|"payment"|"passport";
const nav=[
 ["home","Übersicht",Home],["profile","Kind & Familie",UserRound],["dates","Kurs & Termine",CalendarDays],
 ["health","Gesundheit",HeartPulse],["consent","Einwilligungen",ShieldCheck],["payment","Zahlung",CreditCard],["passport","Dschungelpass",Sparkles]
] as const;
const skills=[["🐒","Klettern & Hangeln",3],["🦩","Balance",2],["🐼","Rollen",2],["🦘","Springen & Landen",2],["🐻","Krabbeln & Stützen",1],["🦜","Koordination",1]] as const;
export default function Page(){
 const [view,setView]=useState<View>("home"),[menu,setMenu]=useState(false),[absence,setAbsence]=useState(false),[reported,setReported]=useState(false),[toast,setToast]=useState("");
 const go=(v:View)=>{setView(v);setMenu(false);scrollTo({top:0,behavior:"smooth"})}; const save=(s:string)=>{setToast(s);setTimeout(()=>setToast(""),2500)};
 return <div className="shell">
  <aside className={menu?"side open":"side"}><button className="side-x" onClick={()=>setMenu(false)}><X/></button><div className="brand"><span>🌿</span><div>Jungle<br/><b>Gymnastics</b></div></div><div className="demo">DEMO · KEINE ECHTDATEN</div><nav>{nav.map(([id,label,Icon])=><button className={view===id?"active":""} onClick={()=>go(id)} key={id}><Icon size={19}/>{label}</button>)}</nav><div className="account"><i>MB</i><div><b>Familie Beispiel</b><small>mia@example.de</small></div></div></aside>
  <main><header><button className="hamb" onClick={()=>setMenu(true)}><Menu/></button><div><small>FAMILIENPORTAL</small><h1>{nav.find(x=>x[0]===view)?.[1]}</h1></div><button className="child"><i>M</i><span><small>Aktives Kind</small><b>Mia Beispiel</b></span><ChevronRight size={16}/></button></header>
  <div className="content">
   {view==="home"&&<Dashboard go={go} absence={()=>setAbsence(true)} reported={reported}/>} 
   {view==="profile"&&<Card title="Kind & Familie" intro="Kontaktdaten für einen sicheren, unkomplizierten Kursalltag."><div className="person"><i>M</i><div><h3>Mia Beispiel</h3><p>Geboren am 18.04.2020 · Klasse GS</p></div><Tag>Aktiv</Tag></div><div className="form"><Field l="Vorname des Kindes" v="Mia"/><Field l="Nachname" v="Beispiel"/><Field l="Geburtsdatum" v="18.04.2020"/><Field l="Klasse" v="GS"/><Field l="Erziehungsberechtigte Person" v="Maria Beispiel"/><Field l="Mobilnummer" v="+49 170 1234567"/><Field l="E-Mail" v="mia@example.de"/><Field l="Weitere Bezugsperson" v="Daniel Beispiel"/></div><button className="primary" onClick={()=>save("Profil gespeichert")}>Änderungen speichern</button></Card>}
   {view==="dates"&&<Dates report={()=>setAbsence(true)} reported={reported}/>} 
   {view==="health"&&<Card title="Gesundheit & Notfall" intro="Nur Angaben, die für eine sichere Betreuung wirklich nötig sind."><Notice icon="♥" title="Bitte aktuell halten">Im Notfall kontaktieren wir zuerst die angegebene Person.</Notice><label>Allergien, Erkrankungen oder wichtige Hinweise<textarea defaultValue="Keine bekannten Allergien."/></label><div className="form"><Field l="Notfallkontakt" v="Maria Beispiel"/><Field l="Telefon im Notfall" v="+49 170 1234567"/></div><label className="check"><input type="checkbox" defaultChecked/> Ich bestätige, dass die Angaben aktuell sind.</label><button className="primary" onClick={()=>save("Gesundheitsangaben gespeichert")}>Sicher speichern</button></Card>}
   {view==="consent"&&<Card title="Foto & Video" intro="Du entscheidest einzeln und kannst deine Auswahl später ändern."><Toggle title="Interne Kursdokumentation" text="Fotos nur für die teilnehmenden Familien." initial/><Toggle title="Informationen der Schule" text="Ausgewählte Aufnahmen in geschützten Schulkanälen."/><Toggle title="Öffentliche Kommunikation" text="Website oder soziale Medien; Namen werden nicht veröffentlicht."/><p className="fine">Eine Ablehnung hat keinen Einfluss auf Mias Teilnahme.</p><button className="primary" onClick={()=>save("Einwilligungen gespeichert")}>Auswahl speichern</button></Card>}
   {view==="payment"&&<Payment/>}{view==="passport"&&<Passport/>}
  </div></main>
  {absence&&<div className="backdrop" onMouseDown={()=>setAbsence(false)}><section className="modal" onMouseDown={e=>e.stopPropagation()}><button className="modal-x" onClick={()=>setAbsence(false)}><X/></button><div className="big-animal">🦜</div><small className="over">SCHNELL GEMELDET</small><h2>Mia ist nicht dabei?</h2><p>Die Abmeldung gilt für den gewählten Kurstermin. Ein Grund ist freiwillig.</p><label>Termin<select><option>Dienstag, 15. September · 14:10</option><option>Dienstag, 22. September · 14:10</option></select></label><label>Hinweis (optional)<textarea placeholder="z. B. Arzttermin"/></label><button className="primary wide" onClick={()=>{setReported(true);setAbsence(false);save("Abwesenheit gemeldet")}}>Abwesenheit melden</button><button className="cancel" onClick={()=>setAbsence(false)}>Abbrechen</button></section></div>}
  {toast&&<div className="toast"><Check size={18}/>{toast}</div>}
 </div>
}
function Dashboard({go,absence,reported}:{go:(v:View)=>void;absence:()=>void;reported:boolean}){return <><section className="hero"><div><small>GUTEN MORGEN, FAMILIE BEISPIEL</small><h2>Mias Dschungel-Abenteuer beginnt.</h2><p>Alles Wichtige zum Kurs an einem ruhigen Ort – schnell erreichbar, auch unterwegs.</p></div><div className="monkey">🐒<b>Los geht’s!</b></div></section><div className="quick-grid"><button className="quick orange" onClick={absence}><i>✋</i><span><small>Schnellaktion</small><b>{reported?"Abwesenheit gemeldet":"Abwesenheit melden"}</b></span><ChevronRight/></button><button className="quick blue" onClick={()=>go("payment")}><i>€</i><span><small>Zahlungsstatus</small><b>Ausstehend · 420 €</b></span><ChevronRight/></button></div><div className="two"><section className="box"><div className="box-head"><div><small className="over">NÄCHSTER TERMIN</small><h3>Jungle Gymnastics</h3></div><Tag>Bestätigt</Tag></div><div className="next"><i><b>15</b><small>SEP</small></i><div><b>Dienstag · 14:10–16:00</b><p>Lycée Jean Renoir · GS</p></div></div><button className="secondary" onClick={()=>go("dates")}>Alle Termine ansehen <ChevronRight size={16}/></button></section><section className="box"><div className="box-head"><div><small className="over">DSCHUNGELPASS</small><h3>11 von 21 Spuren</h3></div><span className="lion">🦁</span></div><div className="bar"><i/></div><p className="muted">Noch 10 Spuren bis zum Dschungel-Champion.</p><div className="animals">{skills.slice(0,5).map(x=><i key={x[0]}>{x[0]}</i>)}</div><button className="secondary" onClick={()=>go("passport")}>Fortschritt öffnen <ChevronRight size={16}/></button></section></div><Notice icon="✓" title="Deine Angaben bleiben geschützt.">Diese Demo speichert keine echten Familien-, Gesundheits- oder Zahlungsdaten.</Notice></>}
function Dates({report,reported}:{report:()=>void;reported:boolean}){return <Card title="Kurs & Termine" intro="Jungle Gymnastics · Dienstags von 14:10 bis 16:00 Uhr."><div className="course"><span>🐒</span><div><b>Lycée Jean Renoir</b><p>GS · Leitung: Rahil Wasiq</p></div></div><div className="dates">{["15. September","22. September","29. September","6. Oktober"].map((d,i)=><div key={d}><i>{i+1}</i><span><b>Dienstag, {d}</b><p>14:10–16:00 · Schulgebäude</p></span>{i===0&&reported?<Tag>Abgemeldet</Tag>:<button onClick={report}>Abmelden</button>}</div>)}</div></Card>}
function Payment(){const[p,setP]=useState("one");return <Card title="Zahlung" intro="Jahresbeitrag für Jungle Gymnastics: 420 €."><div className="pay"><div><small className="over">STATUS</small><h3>Ausstehend</h3><p>Die Zahlungsfunktion wird nach der finalen Schulbestätigung aktiviert.</p></div><b>420 €</b></div><h3>Zahlungsweise vormerken</h3><div className="plans"><button className={p==="one"?"selected":""} onClick={()=>setP("one")}><span><b>Einmalzahlung</b><small>1 × 420 €</small></span>{p==="one"&&<Check/>}</button><button className={p==="four"?"selected":""} onClick={()=>setP("four")}><span><b>Vier Raten</b><small>4 × 105 €</small></span>{p==="four"&&<Check/>}</button></div><button className="primary" disabled>Nach Bestätigung bezahlen</button><p className="fine">Die spätere Zahlung läuft sicher über Stripe. Vollständige Karten- oder Bankdaten werden hier nicht gespeichert.</p></Card>}
function Passport(){return <Card title="Mias Dschungelpass" intro="Kleine Schritte, mutige Bewegungen – jede Spur zeigt, was Mia schon entdeckt hat."><div className="skills">{skills.map(([a,n,count])=><div className="skill" key={n}><i>{a}</i><div><b>{n}</b><p>{count} von 3 Spuren</p><span>{[0,1,2].map(j=><i className={j<count?"done":""} key={j}>{j<count?"✓":""}</i>)}</span></div></div>)}</div><div className="champ"><span>🦁</span><div><small>DAS GROSSE ZIEL</small><h3>Dschungel-Champion</h3><p>Wenn alle Bewegungswelten entdeckt sind, wartet die Löwen-Auszeichnung.</p></div></div></Card>}
function Card({title,intro,children}:{title:string;intro:string;children:React.ReactNode}){return <section className="page"><div className="title"><small>DEMO-PROFIL · MIA BEISPIEL</small><h2>{title}</h2><p>{intro}</p></div>{children}</section>}
function Field({l,v}:{l:string;v:string}){return <label>{l}<input defaultValue={v}/></label>}
function Tag({children}:{children:React.ReactNode}){return <span className="tag">{children}</span>}
function Notice({icon,title,children}:{icon:string;title:string;children:React.ReactNode}){return <section className="notice"><i>{icon}</i><div><b>{title}</b><p>{children}</p></div></section>}
function Toggle({title,text,initial=false}:{title:string;text:string;initial?:boolean}){const[on,setOn]=useState(initial);return <div className="toggle"><div><b>{title}</b><p>{text}</p></div><button className={on?"on":""} onClick={()=>setOn(!on)} role="switch" aria-checked={on}><i/></button></div>}
