"use client";
import {useState} from "react";
import {Home,UserRound,CalendarDays,HeartPulse,ShieldCheck,CreditCard,Sparkles,Menu,X,ChevronRight,Check,Users,ClipboardCheck,Settings,Banknote,BookOpen} from "lucide-react";
type View="home"|"profile"|"dates"|"health"|"consent"|"payment"|"passport";
const nav=[
 ["home","Übersicht",Home],["profile","Kind & Familie",UserRound],["dates","Kurs & Termine",CalendarDays],
 ["health","Gesundheit",HeartPulse],["consent","Einwilligungen",ShieldCheck],["payment","Zahlung",CreditCard],["passport","Dschungelpass",Sparkles]
] as const;
const skills=[["🐒","Klettern & Hangeln",3],["🦩","Balance",2],["🐼","Rollen",2],["🦘","Springen & Landen",2],["🐻","Krabbeln & Stützen",1],["🦜","Koordination",1]] as const;
export default function Page(){
 const [view,setView]=useState<View>("home"),[menu,setMenu]=useState(false),[absence,setAbsence]=useState(false),[reported,setReported]=useState(false),[toast,setToast]=useState(""),[mode,setMode]=useState<"family"|"manager">("family"),[language,setLanguage]=useState("DE");
 const go=(v:View)=>{setView(v);setMenu(false);scrollTo({top:0,behavior:"smooth"})}; const save=(s:string)=>{setToast(s);setTimeout(()=>setToast(""),2500)};
 if(mode==="manager") return <ManagerPortal exit={()=>setMode("family")}/>;
 return <div className="shell">
  <aside className={menu?"side open":"side"}><button className="side-x" onClick={()=>setMenu(false)}><X/></button><div className="brand"><span>TR</span><div>Train With<br/><b>Rahil</b></div></div><div className="demo">DEMO · KEINE ECHTDATEN</div><nav>{nav.map(([id,label,Icon])=><button className={view===id?"active":""} onClick={()=>go(id)} key={id}><Icon size={19}/>{label}</button>)}</nav><button className="manager-link" onClick={()=>setMode("manager")}><Settings size={17}/> Manager-Demo öffnen</button><div className="account"><i>MB</i><div><b>Familie Beispiel</b><small>mia@example.de</small></div></div></aside>
  <main><div className="due-banner"><b>Zahlung offen</b><span>Die erste Barzahlung über 105 € ist seit 1. September fällig.</span><button onClick={()=>go("payment")}>Details ansehen</button></div><header><button className="hamb" onClick={()=>setMenu(true)}><Menu/></button><div><small>FAMILIENPORTAL</small><h1>{nav.find(x=>x[0]===view)?.[1]}</h1></div><select className="language" value={language} onChange={e=>{setLanguage(e.target.value);save(`Sprache: ${e.target.options[e.target.selectedIndex].text}`)}} aria-label="Sprache"><option value="DE">🇩🇪 Deutsch</option><option value="FR">🇫🇷 Français</option><option value="EN">🇬🇧 English</option><option value="ES">🇪🇸 Español</option><option value="AR">🇸🇦 العربية</option><option value="ZH">🇨🇳 中文</option></select><button className="child"><i>M</i><span><small>Aktives Kind</small><b>Mia Beispiel</b></span><ChevronRight size={16}/></button></header>
  <div className="content">
   {view==="home"&&<Dashboard go={go} absence={()=>setAbsence(true)} reported={reported}/>} 
   {view==="profile"&&<Card title="Kind & Familie" intro="Kontaktdaten für einen sicheren, unkomplizierten Kursalltag."><div className="person"><i>M</i><div><h3>Mia Beispiel</h3><p>Geboren am 18.04.2020 · Klasse GS</p></div><Tag>Aktiv</Tag></div><div className="form"><Field l="Vorname des Kindes" v="Mia"/><Field l="Nachname" v="Beispiel"/><Field l="Geburtsdatum" v="18.04.2020"/><Field l="Klasse" v="GS"/><Field l="Erziehungsberechtigte Person" v="Maria Beispiel"/><Field l="Mobilnummer" v="+49 170 1234567"/><Field l="E-Mail" v="mia@example.de"/><Field l="Weitere Bezugsperson" v="Daniel Beispiel"/></div><button className="primary" onClick={()=>save("Profil gespeichert")}>Änderungen speichern</button></Card>}
   {view==="dates"&&<Dates report={()=>setAbsence(true)} reported={reported}/>} 
   {view==="health"&&<Card title="Gesundheit & Notfall" intro="Nur Angaben, die für eine sichere Betreuung wirklich nötig sind."><Notice icon="♥" title="Bitte aktuell halten">Im Notfall kontaktieren wir zuerst die angegebene Person.</Notice><label>Allergien, Erkrankungen oder wichtige Hinweise<textarea defaultValue="Keine bekannten Allergien."/></label><div className="form"><Field l="Notfallkontakt" v="Maria Beispiel"/><Field l="Telefon im Notfall" v="+49 170 1234567"/></div><label className="check"><input type="checkbox" defaultChecked/> Ich bestätige, dass die Angaben aktuell sind.</label><button className="primary" onClick={()=>save("Gesundheitsangaben gespeichert")}>Sicher speichern</button></Card>}
   {view==="consent"&&<Card title="Foto & Video" intro="Du entscheidest einzeln und kannst deine Auswahl später ändern."><Toggle title="Interne Kursdokumentation" text="Fotos nur für die teilnehmenden Familien." initial/><Toggle title="Informationen der Schule" text="Ausgewählte Aufnahmen in geschützten Schulkanälen."/><Toggle title="Öffentliche Kommunikation" text="Website oder soziale Medien; Namen werden nicht veröffentlicht."/><p className="fine">Eine Ablehnung hat keinen Einfluss auf Mias Teilnahme.</p><button className="primary" onClick={()=>save("Einwilligungen gespeichert")}>Auswahl speichern</button></Card>}
   {view==="payment"&&<Payment/>}{view==="passport"&&<Passport/>}
  </div></main>
  {absence&&<div className="backdrop" onMouseDown={()=>setAbsence(false)}><section className="modal" onMouseDown={e=>e.stopPropagation()}><button className="modal-x" onClick={()=>setAbsence(false)}><X/></button><div className="big-animal">🦜</div><small className="over">SCHNELL GEMELDET</small><h2>Mia ist nicht dabei?</h2><p>Die Abmeldung gilt für den gewählten Kurstermin. Ein Grund ist freiwillig.</p><label>Termin<select><option>Dienstag, 15. September · 14:10</option><option>Dienstag, 22. September · 14:10</option></select></label><label>Hinweis (optional)<textarea placeholder="z. B. Arzttermin"/></label><button className="primary wide" onClick={()=>{setReported(true);setAbsence(false);save("Abwesenheit gemeldet")}}>Abwesenheit melden</button><button className="cancel" onClick={()=>setAbsence(false)}>Abbrechen</button></section></div>}
  {toast&&<div className="toast"><Check size={18}/>{toast}</div>}
 </div>
}
function Dashboard({go,absence,reported}:{go:(v:View)=>void;absence:()=>void;reported:boolean}){return <><section className="hero"><div><small>GUTEN MORGEN, FAMILIE BEISPIEL</small><h2>Mias Dschungel-Abenteuer beginnt.</h2><p>Alles Wichtige zum Kurs an einem ruhigen Ort, schnell erreichbar und auch unterwegs.</p></div><div className="monkey"><img src="/jungle-monkey.png" alt="Fröhlicher Affe klettert an einer Liane"/><b>Los geht’s!</b></div></section><div className="quick-grid"><button className="quick orange" onClick={absence}><i>✋</i><span><small>Schnellaktion</small><b>{reported?"Abwesenheit gemeldet":"Abwesenheit melden"}</b></span><ChevronRight/></button><button className="quick blue" onClick={()=>go("payment")}><i>€</i><span><small>Zahlungsstatus</small><b>105 € überfällig</b></span><ChevronRight/></button></div><div className="two"><section className="box"><div className="box-head"><div><small className="over">NÄCHSTER TERMIN</small><h3>Jungle Gymnastics</h3></div><Tag>Bestätigt</Tag></div><div className="next"><i><b>15</b><small>SEP</small></i><div><b>Dienstag · 14:10 bis 16:00</b><p>Lycée Jean Renoir · GS</p></div></div><button className="secondary" onClick={()=>go("dates")}>Alle Termine ansehen <ChevronRight size={16}/></button></section><section className="box"><div className="box-head"><div><small className="over">DSCHUNGELPASS</small><h3>11 von 21 Spuren</h3></div><span className="lion">🦁</span></div><div className="bar"><i/></div><p className="muted">Noch 10 Spuren bis zum Dschungel-Champion.</p><div className="animals">{skills.slice(0,5).map(x=><i key={x[0]}>{x[0]}</i>)}</div><button className="secondary" onClick={()=>go("passport")}>Fortschritt öffnen <ChevronRight size={16}/></button></section></div><Notice icon="✓" title="Deine Angaben bleiben geschützt.">Diese Demo speichert keine echten Familien-, Gesundheits- oder Zahlungsdaten.</Notice></>}
function Dates({report,reported}:{report:()=>void;reported:boolean}){return <Card title="Kurs & Termine" intro="Jungle Gymnastics · Dienstags von 14:10 bis 16:00 Uhr."><div className="course"><span>🐒</span><div><b>Lycée Jean Renoir</b><p>GS · Leitung: Rahil Wasiq</p></div></div><div className="dates">{["15. September","22. September","29. September","6. Oktober"].map((d,i)=><div key={d}><i>{i+1}</i><span><b>Dienstag, {d}</b><p>14:10–16:00 · Schulgebäude</p></span>{i===0&&reported?<Tag>Abgemeldet</Tag>:<button onClick={report}>Abmelden</button>}</div>)}</div></Card>}
function Payment(){const[p,setP]=useState("four"),[saved,setSaved]=useState(false);const rows=p==="four"?["1. Rate · 1. September","2. Rate · 1. November","3. Rate · 1. Januar","4. Rate · 1. März"]:["Gesamtbetrag · 1. September"];return <Card title="Zahlung" intro="Jahresbeitrag für Jungle Gymnastics: 420 €. Die Zahlung erfolgt bar."><div className="pay"><div><small className="over">STATUS</small><h3>Zahlung fällig</h3><p>Der Status wird grün, sobald Rahil den Barbetrag bestätigt.</p></div><b>{p==="four"?"105 €":"420 €"}</b></div><h3>Zahlungsweise wählen</h3><div className="plans"><button className={p==="one"?"selected":""} onClick={()=>setP("one")}><span><b>Alles zusammen</b><small>1 × 420 € bar</small></span>{p==="one"&&<Check/>}</button><button className={p==="four"?"selected":""} onClick={()=>setP("four")}><span><b>Vier Raten</b><small>4 × 105 € bar</small></span>{p==="four"&&<Check/>}</button></div><button className="primary" onClick={()=>setSaved(true)}>{saved?"Auswahl gespeichert":"Zahlungsweise speichern"}</button><div className="installments">{rows.map((x,i)=><div key={x}><span><b>{x}</b><small>{p==="four"?"105 €":"420 €"} · Barzahlung</small></span><em className={i?"pending":"overdue"}>{i?"Offen":"Überfällig"}</em></div>)}</div><p className="fine">Nur der Clubmanager kann eine Barzahlung als erhalten bestätigen.</p></Card>}
function Passport(){return <Card title="Mias Dschungelpass" intro="Kleine Schritte, mutige Bewegungen – jede Spur zeigt, was Mia schon entdeckt hat."><div className="skills">{skills.map(([a,n,count])=><div className="skill" key={n}><i>{a}</i><div><b>{n}</b><p>{count} von 3 Spuren</p><span>{[0,1,2].map(j=><i className={j<count?"done":""} key={j}>{j<count?"✓":""}</i>)}</span></div></div>)}</div><div className="champ"><span>🦁</span><div><small>DAS GROSSE ZIEL</small><h3>Dschungel-Champion</h3><p>Wenn alle Bewegungswelten entdeckt sind, wartet die Löwen-Auszeichnung.</p></div></div></Card>}
function ManagerPortal({exit}:{exit:()=>void}){
 const [section,setSection]=useState("today"),[present,setPresent]=useState([true,false,true,false,false]),[paid,setPaid]=useState([true,false,false,false]);
 const people=["Lina Weber","Mia Beispiel","Noah Martin","Emil Fischer","Sofia Laurent"];
 const items=[["today","Heute",ClipboardCheck],["courses","Kurse",BookOpen],["payments","Barzahlungen",Banknote],["team","Zugänge",Users]] as const;
 return <div className="manager-shell"><aside className="manager-side"><div className="brand"><span>TR</span><div>Train With<br/><b>Rahil</b></div></div><div className="demo">MANAGER · DEMO</div><nav>{items.map(([id,label,Icon])=><button className={section===id?"active":""} key={id} onClick={()=>setSection(id)}><Icon size={19}/>{label}</button>)}</nav><button className="family-return" onClick={exit}><UserRound size={17}/> Familienportal ansehen</button></aside><main className="manager-main"><header><div><small>CLUBMANAGER</small><h1>{items.find(x=>x[0]===section)?.[1]}</h1></div><div className="manager-user"><i>RW</i><span><b>Rahil Wasiq</b><small>Inhaber</small></span></div></header><div className="manager-content">
 {section==="today"&&<><div className="mobile-title"><small>DIENSTAG, 15. SEPTEMBER</small><h2>Jungle Gymnastics</h2><p>14:10 bis 16:00 · GS · 5 Kinder</p></div><div className="stats"><div><b>{present.filter(Boolean).length}</b><span>Anwesend</span></div><div><b>1</b><span>Abgemeldet</span></div><div><b>{present.filter(x=>!x).length}</b><span>Noch offen</span></div></div><section className="attendee-card"><div className="attendee-head"><b>Live Teilnehmerliste</b><span>● Live</span></div>{people.map((name,i)=><div className="attendee" key={name}><i>{name.split(" ").map(x=>x[0]).join("")}</i><span><b>{name}</b><small>{i===1?"Von Familie abgemeldet":i===3?"Hinweis hinterlegt":"Keine Hinweise"}</small></span>{i===1?<em className="absent">Abwesend</em>:<button className={present[i]?"checked":""} onClick={()=>setPresent(a=>a.map((x,j)=>j===i?!x:x))}>{present[i]?<><Check size={17}/> Da</>:"Einchecken"}</button>}</div>)}</section></>}
 {section==="courses"&&<><div className="mobile-title"><small>DEINE ANGEBOTE</small><h2>Kurse flexibel verwalten</h2><p>Zeiten, Plätze, Preise und Fortschritt ohne Neuprogrammierung.</p></div><div className="course-admin"><section><span className="course-art jungle"><img src="/jungle-monkey.png" alt="Jungle Gymnastics"/></span><div><Tag>15 Plätze</Tag><h3>Jungle Gymnastics</h3><p>Dienstag · GS · 14:10 bis 16:00</p><small>6 Bewegungswelten · Dschungelpass</small></div><button>Bearbeiten</button></section><section><span className="course-art hero-badge">⚡</span><div><Tag>15 Plätze</Tag><h3>Superhero Training</h3><p>Donnerstag · CE1 bis CM1 · 14:10 bis 16:00</p><small>Superkraft · Blitzbewegung · Koordination · Ausdauer · Beweglichkeit · Teamgeist</small></div><button>Bearbeiten</button></section></div><button className="primary">Neuen Kurs anlegen</button></>}
 {section==="payments"&&<><div className="mobile-title"><small>BARZAHLUNGEN</small><h2>Zahlungen bestätigen</h2><p>Familien wählen den Plan. Nur du bestätigst erhaltenes Bargeld.</p></div><section className="attendee-card">{["Lina Weber","Mia Beispiel","Noah Martin","Sofia Laurent"].map((name,i)=><div className="attendee payment-row" key={name}><i>€</i><span><b>{name}</b><small>{i===0?"Einmalzahlung · 420 €":"Vier Raten · aktuell 105 €"}</small></span><button className={paid[i]?"checked":""} onClick={()=>setPaid(a=>a.map((x,j)=>j===i?!x:x))}>{paid[i]?<><Check size={17}/> Erhalten</>:"Barzahlung bestätigen"}</button></div>)}</section></>}
 {section==="team"&&<><div className="mobile-title"><small>ROLLEN & RECHTE</small><h2>Zugänge sicher vergeben</h2><p>Jede Person sieht nur die Schulen, Kurse und Funktionen, die du freigibst.</p></div><div className="access-grid"><section><i>RW</i><div><b>Rahil Wasiq</b><p>Inhaber · Vollzugriff</p></div><Tag>Aktiv</Tag></section><section><i>IN</i><div><b>Neue Kursleitung</b><p>Nur Anwesenheit und Fortschritt</p></div><button>Einladen</button></section><section><i>SC</i><div><b>Schulzugang</b><p>Noch nicht aktiviert</p></div><button disabled>Später</button></section></div></>}
 </div></main></div>
}
function Card({title,intro,children}:{title:string;intro:string;children:React.ReactNode}){return <section className="page"><div className="title"><small>DEMO-PROFIL · MIA BEISPIEL</small><h2>{title}</h2><p>{intro}</p></div>{children}</section>}
function Field({l,v}:{l:string;v:string}){return <label>{l}<input defaultValue={v}/></label>}
function Tag({children}:{children:React.ReactNode}){return <span className="tag">{children}</span>}
function Notice({icon,title,children}:{icon:string;title:string;children:React.ReactNode}){return <section className="notice"><i>{icon}</i><div><b>{title}</b><p>{children}</p></div></section>}
function Toggle({title,text,initial=false}:{title:string;text:string;initial?:boolean}){const[on,setOn]=useState(initial);return <div className="toggle"><div><b>{title}</b><p>{text}</p></div><button className={on?"on":""} onClick={()=>setOn(!on)} role="switch" aria-checked={on}><i/></button></div>}
